/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import config.config;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER23
 */
public class costumer_purchase extends javax.swing.JFrame {
Color navcolor = new Color (0,255,255);
Color HEADCOLOR = new Color (255,255,255);
    private String productPrice;
    private int currentProductId;
    
    /**
     * Creates new form costumer_purchase
     */
    public costumer_purchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        wa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        costumer = new javax.swing.JTextField();
        phone_number = new javax.swing.JTextField();
        pn = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        ad = new javax.swing.JLabel();
        was = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("CASH");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        wa.setForeground(new java.awt.Color(255, 255, 255));
        wa.setText("COSTUMER NAME:");
        jPanel2.add(wa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 160, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 260, 170));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CASH:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 262, 50));

        costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costumerActionPerformed(evt);
            }
        });
        jPanel2.add(costumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 249, 50));

        phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numberActionPerformed(evt);
            }
        });
        jPanel2.add(phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 249, 50));

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        pn.setForeground(new java.awt.Color(255, 255, 255));
        pn.setText("PHONE NUMBER:");
        jPanel2.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 140, -1));

        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        jPanel2.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 227, 40));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 249, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUANTITY:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 227, 40));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 227, 46));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRICE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 249, 50));

        ad.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ad.setForeground(new java.awt.Color(255, 255, 255));
        ad.setText("ADDRESS:");
        jPanel2.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 113, 50));

        was.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        was.setForeground(new java.awt.Color(255, 255, 255));
        was.setText("EMAIL:");
        jPanel2.add(was, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 113, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("PURCHASE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, 59));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/image/header_braindiseases.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numberActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void costumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costumerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// 1. Collect inputs from the text fields FIRST
    String custName = costumer.getText();
    String phone = phone_number.getText();
    String mail = email.getText();
    String addr = address.getText();
    String qtyStr = quantity.getText();
    String cashStr = cash.getText();

    // 2. Basic Validation
    if (custName.isEmpty() || qtyStr.isEmpty() || cashStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in Name, Quantity, and Cash!");
        return;
    }

    try {
        // 3. Calculations
        int qtyValue = Integer.parseInt(qtyStr);
        double priceValue = Double.parseDouble(productPrice);
        double total = priceValue * qtyValue;
        double cashValue = Double.parseDouble(cashStr);

        if (cashValue < total) {
            JOptionPane.showMessageDialog(this, "Insufficient Cash! Total: ₱" + total);
            return;
        }

        // 4. Database Operations
        config conf = new config();
        String customerSql = "INSERT INTO customers (full_name, phone, email, address) VALUES (?, ?, ?, ?)";
        conf.addRecord(customerSql, custName, phone, mail, addr);

        String stockSql = "UPDATE products SET stock = stock - ? WHERE product_id = ?";
        conf.addRecord(stockSql, qtyValue, currentProductId);

        // 5. Success & Receipt Generation
        double change = cashValue - total;
        JOptionPane.showMessageDialog(this, "Purchase Successful!\nTotal: ₱" + total + "\nChange: ₱" + change);

        // CREATE THE RECEIPT WINDOW
        receipt rd = new receipt();
        
        // SHOW THE WINDOW FIRST (helps with rendering)
        rd.setVisible(true); 
        
        // NOW PRINT THE DATA TO THE TEXT AREA
        rd.printReceipt(
            custName,               
            jTextField2.getText(), 
            qtyStr,                
            productPrice,          
            String.format("%.2f", total),  
            String.format("%.2f", cashValue), 
            String.format("%.2f", change)     
        );

        this.dispose(); // Close purchase window

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Please enter valid numeric values.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setForeground(HEADCOLOR);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
  jButton1.setForeground(navcolor);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(costumer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(costumer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(costumer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(costumer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new costumer_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JTextField address;
    private javax.swing.JTextField cash;
    private javax.swing.JTextField costumer;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField phone_number;
    private javax.swing.JLabel pn;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel wa;
    private javax.swing.JLabel was;
    // End of variables declaration//GEN-END:variables

    public void setProductDetails(int id, String name, String price, String imgPath) {
        this.currentProductId = id; // Now 'id' is recognized because it's in the ( ) above
        this.productPrice = price; 

        jTextField2.setText(name); 
        jTextField2.setEditable(false); 
        jTextField7.setText(price); 
        jTextField7.setEditable(false);

        if (imgPath != null && !imgPath.isEmpty()) {
            try {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgPath);
                int width = jPanel1.getWidth() > 0 ? jPanel1.getWidth() : 227;
                int height = jPanel1.getHeight() > 0 ? jPanel1.getHeight() : 204;
                java.awt.Image img = icon.getImage().getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
                javax.swing.JLabel imgLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(img));
                jPanel1.setLayout(new java.awt.BorderLayout());
                jPanel1.removeAll();
                jPanel1.add(imgLabel);
                jPanel1.revalidate();
                jPanel1.repaint();
            } catch (Exception e) {
                System.out.println("Image Error: " + e.getMessage());
            }
        }
    } // Closes setProductDetails

    
}