/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;

import config.config;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class userform extends javax.swing.JFrame {
    
    // ... your other methods like displayUser(), chooseProfilePic(), etc.

    private void chooseProfileOrProceed() {
        int selectedRow = userTables.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user first!");
            return;
        }

        int user_id = Integer.parseInt(userTables.getValueAt(selectedRow, 0).toString());
        
        // Check if profile_path already exists
        config con = new config();
        String sqlCheck = "SELECT profile_path FROM users WHERE user_id=? AND is_archived = 0";
        String profilePath = con.getSingleValue(sqlCheck, user_id);
        
        if (profilePath != null && !profilePath.trim().isEmpty()) {
            // Already has profile picture, go straight to dashboard
            staff_profile dash = new staff_profile();
            dash.setVisible(true);
            this.dispose(); // close current form
        } else {
            // No profile picture, let user choose one
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                String path = selectedFile.getAbsolutePath();

                // Update DB
                String sqlUpdate = "UPDATE users SET profile_path=? WHERE user_id=?";
                con.updateRecord(sqlUpdate, path, user_id);

                JOptionPane.showMessageDialog(this, "Profile picture updated!");

                // Now proceed to dashboard
                staff_profile dash = new staff_profile();
                dash.setVisible(true);
                this.dispose();
            }
        }
    }

    public userform() {
    initComponents();   // NetBeans GUI builder code runs first
    displayUser();      // populate the table

    // --- Add the Change Profile Picture button here ---
    JButton changeProfileBtn = new JButton("Change Profile Picture");
    changeProfileBtn.setFont(new java.awt.Font("Arial Black", 1, 18));
    changeProfileBtn.setForeground(new Color(0, 255, 255));
    changeProfileBtn.setBackground(new Color(0, 0, 0));
    // Add using AbsoluteConstraints for NetBeans AbsoluteLayout
    jPanel1.add(changeProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 280, 40));
    // Add action listener
    changeProfileBtn.addActionListener(e -> chooseProfilePic());
    // Repaint panel to show the button
    jPanel1.repaint();
}

Color navcolor = new Color (0,255,255);
Color HEADCOLOR = new Color (255,255,255);
void displayUser(){
 config con = new config();
    String sql = "SELECT * FROM users WHERE is_archived = 0";
    con.displayData(sql, userTables);
    
    // Hide the 'is_archived' column (assuming it's the last column, e.g., index 11)
    // Check your table to confirm which index it is!
    userTables.getColumnModel().getColumn(11).setMinWidth(0);
    userTables.getColumnModel().getColumn(11).setMaxWidth(0);
    userTables.getColumnModel().getColumn(11).setWidth(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        viewArchive = new javax.swing.JLabel();
        Promote = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTables = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 733, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewArchive.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        viewArchive.setForeground(new java.awt.Color(0, 255, 255));
        viewArchive.setText("VIEW ARCHIVE");
        viewArchive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewArchiveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewArchiveMouseEntered(evt);
            }
        });
        jPanel1.add(viewArchive, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 230, 40));

        Promote.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Promote.setForeground(new java.awt.Color(0, 255, 255));
        Promote.setText("PROMOTE");
        Promote.setToolTipText("");
        Promote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PromoteMouseClicked(evt);
            }
        });
        jPanel1.add(Promote, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 170, 40));

        delete.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 255, 255));
        delete.setText("ARCHIVE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 150, 40));

        update.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 255, 255));
        update.setText("ACCEPT");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 130, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERS");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1166, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USERS");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 60));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 60));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HOME");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 60));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SALES");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 60));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOGOUT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 60));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        userTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTables);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/image/Untitled design.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 195, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(HEADCOLOR);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(HEADCOLOR);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(HEADCOLOR);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(navcolor);      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
 int selectedRow = userTables.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user!");
        return;
    }

    // 1. Get User ID from the table (Column 0)
    int userId = Integer.parseInt(userTables.getValueAt(selectedRow, 0).toString());
    String currentStatus = userTables.getValueAt(selectedRow, 3).toString(); // Confirm status is column 3

    config con = new config();

    // 2. Check if the user is archived before allowing an update
    // Note: Changed u_id to user_id to match your archive logic
    String checkSql = "SELECT is_archived FROM users WHERE user_id=?";
    
    // Use the getSingleValue method and parse it, or ensure getIntValue exists in config
    String archivedStatus = con.getSingleValue(checkSql, userId);

    if (archivedStatus != null && archivedStatus.equals("1")) {
        JOptionPane.showMessageDialog(this, "This user is archived and cannot be modified!");
        return;
    }

    // 3. Show Option Dialog
    String[] options = {"Activate", "Keep Pending"};
    int choice = JOptionPane.showOptionDialog(
            this,
            "Current Status: " + currentStatus,
            "Update User Status",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]
    );

    if (choice == -1) return; // User closed the dialog

    String newStatus = (choice == 0) ? "Active" : "Pending";

    // 4. Update the database - Ensure column name is user_id
    String sql = "UPDATE users SET status=? WHERE user_id=?";
    con.updateRecord(sql, newStatus, userId);

    JOptionPane.showMessageDialog(this, "User status updated to: " + newStatus);

    // 5. Refresh table
    displayUser();
    }//GEN-LAST:event_updateMouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(HEADCOLOR); 
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(navcolor);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice == JOptionPane.YES_OPTION) {
        // Open landing
        landing jf = new landing();
        jf.setVisible(true);

        // Close current form
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
product pd = new product();
pd.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
   sales sd = new sales();
sd.setVisible(true);
this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
      jLabel9.setForeground(HEADCOLOR);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
       jLabel8.setForeground(navcolor); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
 int selectedRow = userTables.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to archive!");
        return;
    }

    // Get ID from the first column (user_id)
    String userIdStr = userTables.getValueAt(selectedRow, 0).toString();
    int user_id = Integer.parseInt(userIdStr);
    String userName = userTables.getValueAt(selectedRow, 1).toString();

    // 1. Confirmation Dialog
    int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to archive " + userName + "?", 
            "Confirm Archive", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        config con = new config();
        
        // 2. Perform Update
        String sql = "UPDATE users SET is_archived = 1 WHERE user_id = ?";
        con.updateRecord(sql, user_id);

        // 3. Success Message and Refresh
        JOptionPane.showMessageDialog(this, userName + " has been archived.");
        displayUser(); // This re-runs the SELECT query with WHERE is_archived = 0
     // refresh table
    }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void viewArchiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewArchiveMouseClicked
config con = new config();
    // Switch the query based on what the admin wants to see
    String sql = "SELECT * FROM users WHERE is_archived = 1";
    con.displayData(sql, userTables);

    // Change the 'Archive' label/button text to 'Restore'
    delete.setText("RESTORE");        // TODO add your handling code here:
    }//GEN-LAST:event_viewArchiveMouseClicked

    private void PromoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromoteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PromoteMouseClicked

    private void viewArchiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewArchiveMouseEntered
      jLabel9.setForeground(HEADCOLOR);  // TODO add your handling code here:
    }//GEN-LAST:event_viewArchiveMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Promote;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel update;
    private javax.swing.JTable userTables;
    private javax.swing.JLabel viewArchive;
    // End of variables declaration//GEN-END:variables

    private void chooseProfilePic() {
    JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String path = selectedFile.getAbsolutePath();

        int selectedRow = userTables.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user first!");
            return;
        }
        int user_id = Integer.parseInt(userTables.getValueAt(selectedRow, 0).toString());

        config con = new config();
        String sqlUpdate = "UPDATE users SET profile_path=? WHERE user_id=?";
        con.updateRecord(sqlUpdate, path, user_id);

        JOptionPane.showMessageDialog(this, "Profile picture updated!");
    }
}
}
